# Generated by Django 4.2.13 on 2024-05-16 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dog_adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adoption', to='dog_adoption.dog')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoptions', to='dog_adoption.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
